Teste-Lyncas/src/main/java/br/com/lyncas/model/RespostaQuestao.java
package br.com.lyncas.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class RespostaQuestao {

	@Id
	@GeneratedValue
	private long id;

	@Column(nullable = false, unique = true)
	private String descricaoResposta;
	@Column(nullable = false)
	private boolean verdadeira;

	@ManyToOne(optional = false, fetch = FetchType.EAGER)
	private Questao questao;

	public Questao getQuestao() {
		return questao;
	}

	public void setQuestao(Questao questao) {
		this.questao = questao;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescricaoResposta() {
		return descricaoResposta;
	}

	public void setDescricaoResposta(String descricaoResposta) {
		this.descricaoResposta = descricaoResposta;
	}

	public boolean getVerdadeira() {
		return verdadeira;
	}

	public void setVerdadeira(boolean verdadeira) {
		this.verdadeira = verdadeira;
	}

	@Override
	public String toString() {
		return "RespostaQuestao [id=" + id + ", descricaoResposta=" + descricaoResposta + ", verdadeira=" + verdadeira
				+ ", questao=" + questao + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (id ^ (id >>> 32));
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		RespostaQuestao other = (RespostaQuestao) obj;
		if (id != other.id)
			return false;
		return true;
	}

}

Teste-Lyncas/src/main/java/br/com/lyncas/managedBean/ProvaManagedBean.java
package br.com.lyncas.managedBean;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.com.lyncas.dao.DaoProva;
import br.com.lyncas.model.Prova;

@ManagedBean(name = "provaManegedBean")
@ViewScoped
public class ProvaManagedBean {

	private Prova prova = new Prova();
	private List<Prova> provas = new ArrayList<Prova>();
	private DaoProva<Prova> daoGeneric = new DaoProva<Prova>();

	@PostConstruct
	public void init() {
		provas = daoGeneric.selectAll(Prova.class);
	}

	public Prova getProva() {
		return prova;
	}

	public void setProva(Prova prova) {
		this.prova = prova;
	}

	public String insertProva() {
		try {

			if (prova.getDescricao() == null || prova.getDescricao() == "") {
				FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN,
						"Informação", "O campo Descrição é de preenchimento obrigatório!!!"));

			} else {
				daoGeneric.insert(prova);
				provas.add(prova);

				FacesContext.getCurrentInstance().addMessage(null,
						new FacesMessage(FacesMessage.SEVERITY_INFO, "Informação", "Prova cadastrada com sucesso!!!"));

				newProva();
			}

		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Informação", "Erro ao cadastrar a prova, descrição já cadastrada!!!"));
			newProva();

		}

		return "";
	}

	public String newProva() {
		prova = new Prova();

		return "";
	}

	public List<Prova> getListProva() {
		return provas;
	}

	public String deleteProva() {
		try {
			daoGeneric.removeProva(prova);
			provas.remove(prova);
			prova = new Prova();
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_INFO, "Informação", "Dados removidos com sucesso!!!"));

		} catch (Exception e) {
			System.out.println("ERRO NO DELETE PROVA");
			e.printStackTrace();
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR, "Informação", "Erro ao remover os dados!!!"));
		}
		return "";
	}

}

Teste-Lyncas/WebContent/cadPessoas.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>
		<h:form id="cadPessoas">
			<div style="margin-top: 20px;">
				<h:messages showDetail="true" showSummary="false" />
				<h:panelGrid columns="2">

					<h:outputLabel value="ID:" />
					<h:outputText readonly="true" value="#{pessoaManagedBean.pessoa.id}" />

					<h:outputLabel value="Nome:" />
					<h:inputText value="#{pessoaManagedBean.pessoa.nome}"
						requiredMessage="Informe o nome" />

					<h:outputLabel value="E-Mail:" />
					<h:inputText value="#{pessoaManagedBean.pessoa.email}"
						requiredMessage="Informe o E-Mail" />

					<h:outputLabel value="Tipo:" />
					<h:selectOneMenu id="console"
						value="#{pessoaManagedBean.pessoa.tipo}" style="width: 177px;">
						<f:selectItem itemLabel="Selecione uma opção" itemValue="" />
						<f:selectItem itemLabel="Aluno" itemValue="Aluno" />
						<f:selectItem itemLabel="Especialista" itemValue="Especialista" />
					</h:selectOneMenu>

					<h:outputLabel value="Senha:" />
					<h:inputSecret value="#{pessoaManagedBean.pessoa.senha}"
						requiredMessage="Informe a senha" />

				</h:panelGrid>

				<br />
				<h:commandButton value="Salvar"
					action="#{pessoaManagedBean.insertPessoa}"
					style="width: 100px; margin-left: 20px;" />
				<h:commandButton value="Novo"
					action="#{pessoaManagedBean.newPessoa}"
					style="width: 100px; margin-left: 20px;" />
			</div>
		</h:form>
		
		<h:form id="listPessoas">
			<div style="margin-top: 20px;">
				<p:dataTable value="#{pessoaManagedBean.listPessoas}" var="pessoas"
					style="width: 70%; margin: auto;">
					<f:facet name="header">Lista de Pessoas Cadastradas</f:facet>
					<p:column headerText="Id" style="width: 60px;">
						<h:outputText value="#{pessoas.id}" />
					</p:column>
					<p:column headerText="Nome" style="width: 200px;">
						<h:outputText value="#{pessoas.nome}" />
					</p:column>
					<p:column headerText="E-Mail" style="width: 250px;">
						<h:outputText value="#{pessoas.email}" />
					</p:column>
					<p:column headerText="Tipo"
						style="width: 80px; text-align: center;">
						<h:outputText value="#{pessoas.tipo}" />
					</p:column>
					<p:column headerText="Editar"
						style="width: 90px; text-align: center;">
						<h:commandLink value="Editar" id="btnEdit">
							<f:setPropertyActionListener value="#{pessoas}"
								target="#{pessoaManagedBean.pessoa}" />
							<f:ajax execute="btnEdit" render="@form :cadPessoas" />
						</h:commandLink>
					</p:column>
					<p:column headerText="Remover"
						style="width: 90px; text-align: center;">
						<h:commandLink value="Remover"
							action="#{pessoaManagedBean.deletePessoa}">
							<f:setPropertyActionListener value="#{pessoas}"
								target="#{pessoaManagedBean.pessoa}" />
						</h:commandLink>
					</p:column>
				</p:dataTable>
			</div>
		</h:form>
	</main>
</h:body>
</html>

Teste-Lyncas/WebContent/cadProva.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>

		<h:form id="cadProva">
			<div style="margin-top: 20px;">
				<h:messages showDetail="true" showSummary="false" id="msg" />
				<h:panelGrid columns="2">

					<h:outputLabel value="ID:" />
					<h:outputText readonly="true" value="#{provaManegedBean.prova.id}" />

					<h:outputLabel value="Descrição:" />
					<h:inputText value="#{provaManegedBean.prova.descricao}"/>

					<h:outputLabel value="Status:" />
					<p:selectBooleanCheckbox value="#{provaManegedBean.prova.ativa}" />

				</h:panelGrid>

				<br />
				<h:commandButton value="Salvar"
					action="#{provaManegedBean.insertProva}"
					style="width: 100px; margin-left: 20px;" />
				<h:commandButton value="Novo" action="#{provaManegedBean.newProva}"
					style="width: 100px; margin-left: 20px;" />
			</div>
		</h:form>

		<h:form id="listProvas">
			<div style="margin-top: 20px;">
				<p:dataTable value="#{provaManegedBean.listProva}" var="provas"
					style="width: 70%; margin: auto;">
					<f:facet name="header">Lista de Provas Cadastradas</f:facet>
					<p:column headerText="Id" style="width: 60px;">
						<h:outputText value="#{provas.id}" />
					</p:column>
					<p:column headerText="Descrição" style="width: 200px;">
						<h:link outcome="./cadQuestaoProva.xhtml" value="#{provas.descricao}">
							<f:param name="provaId" value="#{provas.id}" />
						</h:link>
					</p:column>
					<p:column headerText="Status" style="width: 250px;">
						<h:outputText value="#{provas.ativa}" />
					</p:column>
					<p:column headerText="Total realizadas"
						style="width: 80px; text-align: center;">
						<h:outputText value="#{provas.totalRealizadas}" />
					</p:column>
					<p:column headerText="Editar"
						style="width: 90px; text-align: center;">
						<h:commandLink value="Editar" immediate="true" id="btnEdit">
							<f:setPropertyActionListener value="#{provas}"
								target="#{provaManegedBean.prova}" />
							<f:ajax execute="btnEdit" render="@form :cadProva" />
						</h:commandLink>
					</p:column>
					<p:column headerText="Remover"
						style="width: 90px; text-align: center;">
						<h:commandLink immediate="true" value="Remover"
							action="#{provaManegedBean.deleteProva}" id="btnRemover">
							<f:setPropertyActionListener value="#{provas}"
								target="#{provaManegedBean.prova}" />
							<f:ajax execute="btnRemover" render="@form :cadProva:msg"/>
						</h:commandLink>
					</p:column>
				</p:dataTable>
			</div>


		</h:form>
	</main>
</h:body>
</html>

Teste-Lyncas/WebContent/cadQuestaoProva.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>

		<h:form id="cadQuestao">
			<div style="margin-top: 20px;">
				<h:messages showDetail="true" showSummary="false" id="msg" />
				<h:panelGrid columns="2">

					<h:outputLabel value="Descrição da prova:" />
					<h:outputText value="#{questoaManagedBean.prova.descricao}" />

					<h:outputLabel value="ID:" />
					<h:outputText readonly="true"
						value="#{questoaManagedBean.questao.id}" />

					<h:outputLabel value="Título:" />
					<h:inputTextarea value="#{questoaManagedBean.questao.titulo}"
						style="width: 500px; height: 200px;" />

				</h:panelGrid>

				<br />
				<h:commandButton value="Salvar"
					action="#{questoaManagedBean.insertQuestaoProva}"
					style="width: 100px; margin-left: 20px;" />
				<h:commandButton value="Novo"
					action="#{questoaManagedBean.newQuestaoProva}"
					style="width: 100px; margin-left: 20px;" />

			</div>
		</h:form>

		<h:form id="listQuestoes">
			<div style="margin-top: 20px;">
				<p:dataTable value="#{questoaManagedBean.prova.questoes}" var="questoes"
					style="width: 70%; margin: auto;">
					<f:facet name="header">Lista das Questões de Provas Cadastradas</f:facet>
					<p:column headerText="Id" style="width: 60px;">
						<h:outputText value="#{questoes.id}" />
					</p:column>
					<p:column headerText="Título da questão" style="width: 200px;">
						<h:link outcome="./respostaQuestao.xhtml" value="#{questoes.titulo}">
							<f:param name="questaoId" value="#{questoes.id}" />
						</h:link>
					</p:column>
					<p:column headerText="Prova"
						style="width: 80px; text-align: center;">
						<h:outputText value="#{questoaManagedBean.prova.descricao}" />
					</p:column>
					<p:column headerText="Editar"
						style="width: 90px; text-align: center;">
						<h:commandLink value="Editar" immediate="true" id="btnEdit">
							<f:setPropertyActionListener value="#{questoes}"
								target="#{questoaManagedBean.questao}" />
							<f:ajax execute="btnEdit" render="@form :cadQuestao" />
						</h:commandLink>
					</p:column>
					<p:column headerText="Remover"
						style="width: 90px; text-align: center;">
						<h:commandLink immediate="true" value="Remover"
							action="#{questoaManagedBean.deleteQuestao}" id="btnRemover">
							<f:setPropertyActionListener value="#{questoes}"
								target="#{questoaManagedBean.questao}" />
							<f:ajax execute="btnRemover" render="@form :cadQuestao:msg" />
						</h:commandLink>
					</p:column>
				</p:dataTable>
			</div>


		</h:form>

	</main>
</h:body>
</html>

Teste-Lyncas/WebContent/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
	<h:outputStylesheet library="styles" name="style.css" />
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>
		<h:graphicImage library="assets" name="lyncas.jpg" styleClass="background" />
	</main>
</h:body>
</html>

Teste-Lyncas/WebContent/login.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>
		<h:form>
			<h:messages showDetail="true" showSummary="false" id="msg"/>
			<h:outputLabel value="Login:" />
			<h:inputText value="#{loginManagedBean.email}" /><br />
			<h:outputLabel value="Senha:" />
			<h:inputText value="#{loginManagedBean.senha}" /><br />
			<h:commandButton action="#{loginManagedBean.logar}" value="Entrar" />
		</h:form>
		
	</main>
</h:body>
</html>

Teste-Lyncas/WebContent/menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>
</h:head>

<h:body>
	<h:form>
		<p:growl id="messages" />

		<p:menubar>
			<p:menuitem value="Home" url="index.xhtml" />
			<p:submenu label="Cadastros">
				<p:menuitem value="Pessoas" url="cadPessoas.xhtml"/>
				<p:menuitem value="Provas" url="cadProva.xhtml"/>
			</p:submenu>
		</p:menubar>
	</h:form>
</h:body>
</html>

Teste-Lyncas/WebContent/respostaQuestao.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

<h:head>
</h:head>

<h:body>
	<header>
		<ui:include src="./menu.xhtml" />
	</header>

	<main>

		<h:form id="cadResposta">
			<div style="margin-top: 20px;">
				<h:messages showDetail="true" showSummary="false" id="msg" />
				<h:panelGrid columns="2">

					<h:outputLabel value="Descrição da questão:" />
					<h:outputText value="#{respostaManagedBean.questao.titulo}" />

					<h:outputLabel value="ID:" />
					<h:outputText readonly="true"
						value="#{respostaManagedBean.respostaQuestao.id}" />

					<h:outputLabel value="Descrição de resposta:" />
					<h:inputTextarea value="#{respostaManagedBean.respostaQuestao.descricaoResposta}"
						style="width: 500px; height: 200px;" />
					
					<h:outputLabel value="Resposta verdadeira:" />
					<p:selectBooleanCheckbox value="#{respostaManagedBean.respostaQuestao.verdadeira}" />

				</h:panelGrid>

				<br />
				<h:commandButton value="Salvar"
					action="#{respostaManagedBean.insertResposta}"
					style="width: 100px; margin-left: 20px;" />
				<h:commandButton value="Novo"
					action="#{respostaManagedBean.newResposta}"
					style="width: 100px; margin-left: 20px;" />

			</div>
		</h:form>

		<h:form id="listRespostas">
			<div style="margin-top: 20px;">
				<p:dataTable value="#{respostaManagedBean.questao.respostasQuestao}" var="respostas"
					style="width: 70%; margin: auto;">
					<f:facet name="header">Lista das Questões de Provas Cadastradas</f:facet>
					<p:column headerText="Id" style="width: 60px;">
						<h:outputText value="#{respostas.id}" />
					</p:column>
					<p:column headerText="Questão"
						style="width: 80px; text-align: center;">
						<h:outputText value="#{respostaManagedBean.questao.titulo}" />
					</p:column>
					<p:column headerText="Descrição da resposta" style="width: 200px;">
						<h:outputText value="#{respostas.descricaoResposta}" />
					</p:column>
					<p:column headerText="Resposta correta" style="width: 200px;">
						<h:outputText value="#{respostas.verdadeira}" />
					</p:column>
					<p:column headerText="Editar"
						style="width: 90px; text-align: center;">
						<h:commandLink value="Editar" immediate="true" id="btnEdit">
							<f:setPropertyActionListener value="#{respostas}"
								target="#{respostaManagedBean.respostaQuestao}" />
							<f:ajax execute="btnEdit" render="@form :cadResposta" />
						</h:commandLink>
					</p:column>
					<p:column headerText="Remover"
						style="width: 90px; text-align: center;">
						<h:commandLink immediate="true" value="Remover"
							action="#{respostaManagedBean.deleteResposta}" id="btnRemover">
							<f:setPropertyActionListener value="#{respostas}"
								target="#{respostaManagedBean.respostaQuestao}" />
							<f:ajax execute="btnRemover" render="@form :cadResposta:msg" />
						</h:commandLink>
					</p:column>
				</p:dataTable>
			</div>


		</h:form>

	</main>
</h:body>
</html>